title: Writeups! # name of the site
author: P3t3x  # name of site's author
email:  # email of site's author
url:  # root address of the site
description: > # description of the site (multiple lines allowed)
  En el viaje hacia el OSCP - decidi hacer un writeup de cada maquina en la lista de TJ_Null y la lista de The Mayor
  tambien un post sobre la metodologia para el examen y la aventura en general.

permalink: /:slug.html

favicon: "./logo.png" # relative path to site's favicon
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

remote theme: riggraz/no-style-please

theme_config:
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
