title: Writeups! # name of the site
author: P3T3x # name of site's author
email: noemail@gmail.com # email of site's author
url: https://petesect18.github.io/writeups # root address of the site
description: > # description of the site (multiple lines allowed)
  En preparacion para el OSCP, diferentes writeups de la lista de TJ Null y The Mayor.

permalink: /:slug.html

favicon: "./logo.png" # relative path to site's favicon
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

theme: no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
